// Generated by CoffeeScript 1.9.3
(function() {
  var gulp, requireDir, runSequence;

  gulp = require('gulp');

  requireDir = require('require-dir');

  runSequence = require('run-sequence');

  requireDir('./gulp/tasks', {
    recurse: true
  });

  gulp.task('default', ['server']);

  gulp.task('build', ['clean'], function(cb) {
    return runSequence(['partials', 'scripts', 'html', 'sass', 'images'], cb);
  });

  gulp.task('server', ['setWatch', 'build'], function() {
    return gulp.start('watch');
  });

}).call(this);

//# sourceMappingURL=gulpfile.js.map
