// Generated by CoffeeScript 1.9.3
(function() {
  var del, gulp;

  gulp = require('gulp');

  del = require('del');

  gulp.task('clean', function(cb) {
    return del('./build', cb);
  });

}).call(this);

//# sourceMappingURL=clean.js.map
