// Generated by CoffeeScript 1.9.3
(function() {
  var browserSync, gulp, reload;

  gulp = require('gulp');

  browserSync = require('browser-sync');

  reload = browserSync.reload;

  gulp.task('images', function() {
    return gulp.src('./app/i/*.png').pipe(gulp.dest('./build/i')).pipe(reload({
      stream: true
    }));
  });

}).call(this);

//# sourceMappingURL=images.js.map
