// Generated by CoffeeScript 1.9.3
(function() {
  var browserSync, fileinclude, gulp, reload, rename;

  gulp = require('gulp');

  fileinclude = require('gulp-file-include');

  rename = require('gulp-rename');

  browserSync = require('browser-sync');

  reload = browserSync.reload;

  gulp.task('partials', function() {
    return gulp.src('./app/html/partials/*.tpl.html').pipe(fileinclude()).pipe(rename({
      extname: ""
    })).pipe(rename({
      extname: ".html"
    })).pipe(gulp.dest('./app/html/'));
  });

}).call(this);

//# sourceMappingURL=partials.js.map
