// Generated by CoffeeScript 1.9.3
(function() {
  var $, foundation, foundationorbit;

  console.log("Hello");

  $ = require('jquery');

  global.jQuery = $;

  foundation = require('foundation');

  foundationorbit = require('foundationorbit');

  $(document).foundation();

}).call(this);

//# sourceMappingURL=main.js.map
